name: Lets play basketball

on:
  schedule:
    # Запускать каждый понедельник и среду в 12:00 по UTC (15:00 по Москве)
    - cron: '0 12 * * 1,3'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  send-poll:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send poll to Telegram channel
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python bot.py

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
      github.rest.issues.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title: 'Ошибка отправки опроса',
        body: 'Workflow по отправке опроса завершился с ошибкой'
      })
