name: Get Group ID

on:
  workflow_dispatch:

jobs:
  get-group-id:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==20.7 python-dotenv
        
    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        
    - name: Run get_group_id script
      run: |
        echo "Этот скрипт будет работать 5 минут. За это время:"
        echo "1. Добавьте бота в группу"
        echo "2. Отправьте сообщение в группе"
        echo "3. ID группы появится в логах ниже"
        timeout 300s python get_group_id.py
