name: Basketball Poll Bot

on:
  schedule:
    # Понедельник и среда в 9:00 UTC (12:00 по Москве)
    - cron: '0 9 * * 1'  # Понедельник в 9:00 UTC
    - cron: '0 9 * * 3'  # Среда в 9:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  send-poll:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==13.7
        
    - name: Send poll to Telegram group
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
      run: python bot.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bot-logs
        path: "*.log"
