name: Basketball Poll Bot

on:
  schedule:
    # Понедельник и среда в 12:00 по Москве (9:00 UTC)
    - cron: '0 9 * * 1,3'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  send-poll:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send poll to Telegram channel
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python bot.py
