name: Basketball Poll Bot

on:
  schedule:
    - cron: '0 9 * * 1,3'  # Понедельник и среда в 12:00 по Москве (9:00 UTC)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  send-poll:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send poll to Telegram group
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}  # ID закрытой группы
      run: python bot.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bot-logs
        path: logs/
